from pathlib import Path
import pandas as pd
import re

FIGHTS_FILE = Path(__file__).resolve().parent.parent / "Data" / "ufc_fights.csv"
FIGHTERS_FILE = Path(__file__).resolve().parent.parent / "Data" / "ufc_fighters.csv"

# ─────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────

def clean_nan(df: pd.DataFrame) -> pd.DataFrame:
    """Replace NaN, 'nan', 'NaN', 'None' strings with empty string."""
    df = df.fillna("")
    for col in df.columns:
        df[col] = df[col].astype(str).str.strip()
        df[col] = df[col].replace({"nan": "", "NaN": "", "None": "", "none": ""})
        # Clean nan+unit combinations like 'nancm', 'nan"', 'nanlbs'
        df[col] = df[col].replace(to_replace=r'^nan\S*$', value="", regex=True)
    return df


def clean_numeric(df: pd.DataFrame, columns: list) -> pd.DataFrame:
    """Remove non-numeric chars from numeric columns, keep empty if invalid."""
    for col in columns:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").fillna("").astype(str)
            df[col] = df[col].replace({"nan": "", "NaN": ""})
    return df


def clean_integer(df: pd.DataFrame, columns: list) -> pd.DataFrame:
    """Convert float-looking integers like 170.0 to 170."""
    for col in columns:
        if col in df.columns:
            numeric = pd.to_numeric(df[col], errors="coerce")
            df[col] = numeric.apply(
                lambda x: str(int(x)) if pd.notna(x) else ""
            )
    return df


def clean_percentage(df: pd.DataFrame, columns: list) -> pd.DataFrame:
    """Ensure percentage columns are between 0 and 1, remove outliers."""
    for col in columns:
        if col in df.columns:
            numeric = pd.to_numeric(df[col], errors="coerce")
            if numeric.dropna().max() > 1:
                numeric = numeric / 100
            df[col] = numeric.round(4).fillna("").astype(str)
            df[col] = df[col].replace({"nan": "", "NaN": ""})
    return df


def fix_swapped_date_location(df: pd.DataFrame) -> pd.DataFrame:
    """
    Detect and fix swapped event_date and event_location columns.
    This happened in CSVs generated by old versions of the scraper.
    """
    if "event_date" not in df.columns or "event_location" not in df.columns:
        return df

    sample = df["event_date"].replace("", pd.NA).dropna().head(20)
    if sample.empty:
        return df

    location_pattern = re.compile(r"\b(USA|UK|Brazil|Canada|Australia|Nevada|California|Florida|England|Japan)\b", re.I)
    date_pattern = re.compile(r"\b(January|February|March|April|May|June|July|August|September|October|November|December|\d{4})\b", re.I)

    date_col_looks_like_location = sample.str.contains(location_pattern).mean() > 0.5
    date_col_looks_like_date = sample.str.contains(date_pattern).mean() > 0.5

    if date_col_looks_like_location and not date_col_looks_like_date:
        print("  [FIX] Detected swapped event_date and event_location columns — fixing...")
        df["event_date"], df["event_location"] = df["event_location"].copy(), df["event_date"].copy()
        print("  [FIX] Columns swapped successfully.")
    else:
        print("  [OK] event_date and event_location columns look correct.")

    return df


def report(df: pd.DataFrame, name: str) -> None:
    print(f"\n{'='*50}")
    print(f"  {name}")
    print(f"{'='*50}")
    print(f"  Rows: {len(df)}")
    empty_cols = [(col, df[col].replace('', pd.NA).isna().sum()) for col in df.columns if df[col].replace('', pd.NA).isna().sum() > 0]
    if empty_cols:
        print(f"  Columns with empty values:")
        for col, count in sorted(empty_cols, key=lambda x: -x[1]):
            pct = count / len(df) * 100
            print(f"    {col}: {count} empty ({pct:.1f}%)")
    else:
        print("  All columns complete!")


# ─────────────────────────────────────────
# CLEAN FIGHTS
# ─────────────────────────────────────────

def clean_fights() -> None:
    if not FIGHTS_FILE.exists():
        print(f"[SKIP] {FIGHTS_FILE} not found.")
        return

    print(f"\nCleaning {FIGHTS_FILE.name}...")
    df = pd.read_csv(FIGHTS_FILE, dtype=str, encoding="utf-8-sig", keep_default_na=False)

    df = clean_nan(df)
    df = fix_swapped_date_location(df)

    numeric_cols = [
        "knockdowns_1", "knockdowns_2",
        "total_strikes_landed_1", "total_strikes_att_1",
        "total_strikes_landed_2", "total_strikes_att_2",
        "significant_strikes_landed_1", "significant_strikes_att_1",
        "significant_strikes_landed_2", "significant_strikes_att_2",
        "sig_strikes_head_1", "sig_strikes_head_2",
        "sig_strikes_body_1", "sig_strikes_body_2",
        "sig_strikes_leg_1", "sig_strikes_leg_2",
        "distance_strikes_1", "distance_strikes_2",
        "clinch_strikes_1", "clinch_strikes_2",
        "ground_strikes_1", "ground_strikes_2",
        "takedowns_att_1", "takedowns_succ_1",
        "takedowns_att_2", "takedowns_succ_2",
        "control_time_seconds_1", "control_time_seconds_2",
        "subs_att_1", "subs_att_2",
        "reversals_1", "reversals_2",
    ]
    df = clean_numeric(df, numeric_cols)

    pct_cols = [
        "sig_strikes_accuracy_1", "sig_strikes_accuracy_2",
        "sig_strikes_defense_1", "sig_strikes_defense_2",
        "takedowns_pct_1", "takedowns_pct_2",
        "takedowns_defense_1", "takedowns_defense_2",
    ]
    df = clean_percentage(df, pct_cols)

    if "method" in df.columns:
        df["method"] = df["method"].str.strip()

    df.to_csv(FIGHTS_FILE, index=False, encoding="utf-8-sig")
    report(df, FIGHTS_FILE.name)
    print(f"  Saved: {FIGHTS_FILE}")


# ─────────────────────────────────────────
# CLEAN FIGHTERS
# ─────────────────────────────────────────

def clean_fighters() -> None:
    if not FIGHTERS_FILE.exists():
        print(f"[SKIP] {FIGHTERS_FILE} not found.")
        return

    print(f"\nCleaning {FIGHTERS_FILE.name}...")
    df = pd.read_csv(FIGHTERS_FILE, dtype=str, encoding="utf-8-sig", keep_default_na=False)

    df = clean_nan(df)

    # Convert float integers to clean integers (170.0 -> 170)
    integer_cols = ["height_cm", "weight_lbs", "reach_cm", "wins", "losses", "draws", "no_contests"]
    df = clean_integer(df, integer_cols)

    float_cols = ["slpm", "sapm", "td_avg", "sub_avg"]
    for col in float_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").round(2).fillna("").astype(str)
            df[col] = df[col].replace({"nan": "", "NaN": ""})

    pct_cols = ["str_acc", "str_def", "td_acc", "td_def"]
    df = clean_percentage(df, pct_cols)

    if "stance" in df.columns:
        df["stance"] = df["stance"].str.strip().str.title()
        df["stance"] = df["stance"].replace({"Nan": "", "nan": ""})

    if "date_of_birth" in df.columns:
        df["date_of_birth"] = pd.to_datetime(
            df["date_of_birth"], errors="coerce"
        ).dt.strftime("%Y-%m-%d").fillna("")

    df.to_csv(FIGHTERS_FILE, index=False, encoding="utf-8-sig")
    report(df, FIGHTERS_FILE.name)
    print(f"  Saved: {FIGHTERS_FILE}")


# ─────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────

def main() -> None:
    print("Starting data cleaning...")
    clean_fights()
    clean_fighters()
    print("\nAll done!")


if __name__ == "__main__":
    main()
